language: go

go:
  - "1.11.1"

script:
  - go build -o /release
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t cjblink1/srtsignin-data-service:$TRAVIS_COMMIT .
  - docker push cjblink1/srtsignin-data-service:$TRAVIS_COMMIT