language: go

go:
  - "1.11.1"
  
install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - godep save

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t cjblink1/srtsignin-data-service:$TRAVIS_COMMIT .
  - docker push cjblink1/srtsignin-data-service:$TRAVIS_COMMIT