language: go

go:
  - "1.11.1"
  
go_import_path: github.com/srtsignin/DataService

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t cjblink1/srtsignin-data-service:$TRAVIS_COMMIT .
  - docker push cjblink1/srtsignin-data-service:$TRAVIS_COMMIT